### ISSUE TITLE
Filter files

### ISSUE THREAD

**Issue by panosdim** [akout/wlFxp#1]
How can i filter the files shown in a directory? i.e. i want to see only the files that have .cfg extension in a specific directory. I tried Command menu but it seems to not working

**Comment by akout** [comment]
Filtering the displayed file list is currently not supported. Maybe it makes sense to add the possibility to use e.g. regular expressions in the path text field?

**Comment by panosdim** [comment]
If it is possible to use regular expressions in the path text field then it
is ok.

**Comment by akout** [comment]
It should be possible now to use the wildcards * and ? in the path text field to show only files that match.
